import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "rsuite/dist/rsuite-no-reset.min.css";
import "@rainbow-me/rainbowkit/styles.css";

import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

import "./globals.css";

import { LayoutProviders } from "@/provider/LayoutProviders";

import Nav from "components/Nav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <LayoutProviders>
          <Nav />
          {children}
          <ToastContainer />
        </LayoutProviders>
      </body>
    </html>
  );
}
